name: "Setup Flutter"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2

    - name: Get Dependencies
      shell: bash
      run: flutter pub get